name: powerShell
on: push

jobs:
  pester-test:
    name: powerShell
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Perform a Pester test from the windowCmd.webInstall.ps1 file
        shell: pwsh
        run: |
          Invoke-Pester windowCmd.webInstall.ps1 -Passthru
